version: '3'

services:
  #Backend Django
  backend:
    build: ./backend
    image: survey_progress_backend
    env_file:
      - .env    
    volumes:
      - ./backend:/app
      - ./log:/log
      - ./archive:/archive      
    ports:
      - 8081:8081
    depends_on:
      - database
    networks:
      - survey_progress            

  # Database
  database:
    image: postgres:9.6
    restart: always
    env_file:
      - .env
    expose:
      - 5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./pg_backups:/pg_backups
      - ./database_subset:/data
    networks:
      - survey_progress      

networks:
  survey_progress: