version: '3'

services:
  # Database
  database:
    image: postgres:9.6
    restart: always
    env_file:
      - .env
    # expose:
    #   - 5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./pg_backups:/pg_backups
      - ./database_subset:/data

  #Backend Django
  backend:
    build: ./backend
    image: survey_progress_backend
    env_file:
      - .env    
    volumes:
      - ./backend:/app
      - ./log:/log
      - ./archive:/archive      
    depends_on:
      - database

  # Frontend
  frontend:
    build: ./frontend
    image: survey_progress_frontend
    env_file:
      - .env
      
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./frontend/build:/var/www/frontend
      - ./nginx/conf.d:/etc/nginx/conf.d/default.conf:ro
      - ./log:/log
    depends_on:
      - backend
