version: '3'

services:
  # Database
  database:
    image: postgres:9.6
    restart: always
    env_file:
      - .env
    expose:
      - 5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./pg_backups:/pg_backups
      - ./database_subset:/data
    networks:
      - survey_progress      

  #Backend Django
  backend:
    build: ./backend
    image: survey_progress_backend
    env_file:
      - .env    
    volumes:
      - ./backend:/app
      - ./log:/log
      - ./archive:/archive      
    ports:
      - 8081:8081
    depends_on:
      - database
    networks:
      - survey_progress            

  # Frontend
  frontend:
    build: ./frontend
    image: survey_progress_frontend
    env_file:
      - .env
    ports:
      - 8080:8080
    networks:
      - survey_progress

      
  nginx:
    image: nginx:latest
    ports:
      - 6000:80
    volumes:
      - ./log:/log
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - frontend
      - backend

networks:
  survey_progress: